### ISSUE TITLE
requirement of ruby version !?

### ISSUE THREAD

**Issue by null9beta** [monterail/redis-browser#26]
Hi, 

i jost got a question about the required ruby version, in the README it says
`Ruby Version ">=1.9.2"`

But in fact it seems there is a dependency to mustermann-1.0.0.beta2 which requires a higher version. 

```
$# gem install redis-browser
Fetching: mustermann-1.0.0.beta2.gem (100%)
ERROR:  Error installing redis-browser:
       	mustermann requires Ruby version >= 2.2.0.

$#ruby -v
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
```

**Comment by szajbus** [comment]
@null9beta thanks for pointing that out. Turns out that sinatra now requires ruby 2.2.

I created a new version line for redis-browser `~> 0.4.0` that is now maintained in `ruby-1.9.2+` branch and has a strict dependency of sinatra set to `< 2.0` to remain compatible with ruby 1.9.2+.

The `~> 0.5.0` line and code in `master` branch depends simply on any version of sinatra and can be used with ruby 2.2 and higher.

README has been changed accordingly.
